export const POST_NAMESPACE = 'posts';
export const FILTER_NAMESPACE = 'filter';

export const POST_CREATE = 'POST_CREATE';
export const POST_CREATE_REQUESTED = 'POST_CREATE_REQUESTED';
export const POST_CREATE_SUCCEEDED = 'POST_CREATE_SUCCEEDED';
export const POST_CREATE_FAILED = 'POST_CREATE_FAILED';
export const POST_CREATE_DONE = 'POST_CREATE_DONE';

export const FILTER_CLEAR = 'FILTER_CLEAR';
